name: Update viable/strict

on:
  schedule:
    - cron: 17,47 * * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  do_update_viablestrict:
    if: ${{ github.repository_owner == 'pytorch' }}
    runs-on: ubuntu-20.04
    # TODO: Clean up the else part to restrict the env before landing the change
    environment: ${{ (github.event_name == 'schedule') && 'update-viable-strict' || 'update-viable-strict' }}
    steps:
      - name: Update viable/strict
        uses: pytorch/test-infra/.github/actions/update-viablestrict@main
        with:
          repository: pytorch/executorch
          stable-branch: viable/strict
          requires: '[\"pull\", \"lint\"]'
          secret-bot-token: ${{ secrets.UPDATEBOT_TOKEN }}
          rockset-api-key: ${{ secrets.ROCKSET_API_KEY }}
