name: Upload AWS Device Farm Android test specs

on:
  pull_request:
    paths:
      - .github/workflows/upload-android-test-specs.yml
      - extension/benchmark/android/benchmark/android-llm-device-farm-test-spec.yml.j2
  push:
    branches:
      - main
    paths:
      - .github/workflows/upload-android-test-specs.yml
      - extension/benchmark/android/benchmark/android-llm-device-farm-test-spec.yml.j2

concurrency:
  # NB: This concurency group needs to be different than the one used in android-perf, otherwise
  # GH complains about concurrency deadlock
  group: android-spec-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:
  validate-android-test-spec:
    needs: upload-android-test-spec-for-validation
    uses: ./.github/workflows/android-perf.yml
    permissions:
      id-token: write
      contents: read
    with:
      # Just use a small model here with a minimal amount of configuration to test the spec
      models: stories110M
      devices: samsung_galaxy_s22
      delegates: xnnpack
